//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551dc)
//
// On Thu Jan 11 14:40:52 CST 2024
//
//
// Ports:
// Name                         I/O  size props
// calc_crc                       O    64
// calc_crc_crcIn                 I    64
// calc_crc_data                  I    48
//
// Combinational paths from inputs to outputs:
//   (calc_crc_crcIn, calc_crc_data) -> calc_crc
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_calc_crc(calc_crc_crcIn,
		       calc_crc_data,
		       calc_crc);
  // value method calc_crc
  input  [63 : 0] calc_crc_crcIn;
  input  [47 : 0] calc_crc_data;
  output [63 : 0] calc_crc;

  // signals for module outputs
  wire [63 : 0] calc_crc;

  // remaining internal signals
  wire [59 : 0] calc_crc_crcIn_BIT_43_1_XOR_calc_crc_crcIn_BIT_ETC___d459;
  wire [55 : 0] calc_crc_crcIn_BIT_39_7_XOR_calc_crc_crcIn_BIT_ETC___d457;
  wire [51 : 0] calc_crc_crcIn_BIT_35_3_XOR_calc_crc_crcIn_BIT_ETC___d455;
  wire [47 : 0] calc_crc_crcIn_BIT_31_29_XOR_calc_crc_crcIn_BI_ETC___d453;
  wire [43 : 0] calc_crc_crcIn_BIT_27_65_XOR_calc_crc_crcIn_BI_ETC___d451;
  wire [39 : 0] calc_crc_crcIn_BIT_23_01_XOR_calc_crc_crcIn_BI_ETC___d449;
  wire [35 : 0] calc_crc_crcIn_BIT_19_37_XOR_calc_crc_crcIn_BI_ETC___d447;
  wire [31 : 0] calc_crc_crcIn_BIT_15_73_XOR_calc_crc_crcIn_BI_ETC___d445;
  wire [27 : 0] calc_crc_crcIn_BIT_11_09_XOR_calc_crc_crcIn_BI_ETC___d443;
  wire [23 : 0] calc_crc_crcIn_BIT_7_45_XOR_calc_crc_crcIn_BIT_ETC___d441;
  wire [19 : 0] calc_crc_crcIn_BIT_3_81_XOR_calc_crc_crcIn_BIT_ETC___d439;
  wire [15 : 0] calc_crc_crcIn_BIT_0_08_XOR_calc_crc_crcIn_BIT_ETC___d437;
  wire x__h1007,
       x__h1009,
       x__h1101,
       x__h1103,
       x__h1195,
       x__h1197,
       x__h1199,
       x__h1201,
       x__h1331,
       x__h1333,
       x__h1335,
       x__h1337,
       x__h1339,
       x__h1341,
       x__h1509,
       x__h1511,
       x__h1513,
       x__h1515,
       x__h1517,
       x__h1519,
       x__h1687,
       x__h1689,
       x__h1691,
       x__h1693,
       x__h1695,
       x__h1697,
       x__h1865,
       x__h1867,
       x__h1869,
       x__h1871,
       x__h1873,
       x__h1875,
       x__h2043,
       x__h2045,
       x__h2047,
       x__h2049,
       x__h2051,
       x__h2053,
       x__h2221,
       x__h2223,
       x__h2225,
       x__h2227,
       x__h2229,
       x__h2231,
       x__h2399,
       x__h2401,
       x__h2403,
       x__h2405,
       x__h2407,
       x__h2409,
       x__h2577,
       x__h2579,
       x__h2581,
       x__h2583,
       x__h2585,
       x__h2587,
       x__h2755,
       x__h2757,
       x__h2759,
       x__h2761,
       x__h2763,
       x__h2765,
       x__h2933,
       x__h2935,
       x__h2937,
       x__h2939,
       x__h2941,
       x__h2943,
       x__h3111,
       x__h3113,
       x__h3115,
       x__h3117,
       x__h3119,
       x__h3121,
       x__h3289,
       x__h3291,
       x__h3293,
       x__h3295,
       x__h3297,
       x__h3299,
       x__h3467,
       x__h3469,
       x__h3471,
       x__h3473,
       x__h3475,
       x__h3477,
       x__h3645,
       x__h3647,
       x__h3649,
       x__h3651,
       x__h3653,
       x__h3655,
       x__h3823,
       x__h3825,
       x__h3827,
       x__h3829,
       x__h3831,
       x__h3833,
       x__h4001,
       x__h4003,
       x__h4005,
       x__h4007,
       x__h4009,
       x__h4011,
       x__h4179,
       x__h4181,
       x__h4183,
       x__h4185,
       x__h4187,
       x__h4189,
       x__h4357,
       x__h4359,
       x__h4361,
       x__h4363,
       x__h4365,
       x__h4367,
       x__h4535,
       x__h4537,
       x__h4539,
       x__h4541,
       x__h4543,
       x__h4545,
       x__h4713,
       x__h4715,
       x__h4717,
       x__h4719,
       x__h4721,
       x__h4723,
       x__h4891,
       x__h4893,
       x__h4895,
       x__h4897,
       x__h4899,
       x__h4901,
       x__h5069,
       x__h5071,
       x__h5073,
       x__h5075,
       x__h5077,
       x__h5079,
       x__h5247,
       x__h5249,
       x__h5251,
       x__h5253,
       x__h5255,
       x__h5257,
       x__h5425,
       x__h5427,
       x__h5429,
       x__h5431,
       x__h5433,
       x__h5435,
       x__h5603,
       x__h5605,
       x__h5607,
       x__h5609,
       x__h5611,
       x__h5613,
       x__h5781,
       x__h5783,
       x__h5785,
       x__h5787,
       x__h5789,
       x__h5791,
       x__h5959,
       x__h5961,
       x__h5963,
       x__h5965,
       x__h5967,
       x__h5969,
       x__h6137,
       x__h6139,
       x__h6141,
       x__h6143,
       x__h6145,
       x__h6147,
       x__h6315,
       x__h6317,
       x__h6319,
       x__h6321,
       x__h6323,
       x__h6325,
       x__h6493,
       x__h6495,
       x__h6497,
       x__h6499,
       x__h6501,
       x__h6503,
       x__h6671,
       x__h6673,
       x__h6675,
       x__h6677,
       x__h6679,
       x__h6681,
       x__h6849,
       x__h6851,
       x__h6853,
       x__h6855,
       x__h6857,
       x__h6859,
       x__h7027,
       x__h7029,
       x__h7031,
       x__h7033,
       x__h7035,
       x__h7037,
       x__h7205,
       x__h7207,
       x__h7209,
       x__h7211,
       x__h7213,
       x__h7215,
       x__h7383,
       x__h7385,
       x__h7387,
       x__h7389,
       x__h7391,
       x__h7393,
       x__h7561,
       x__h7563,
       x__h7565,
       x__h7567,
       x__h7569,
       x__h7571,
       x__h7739,
       x__h7741,
       x__h7743,
       x__h7745,
       x__h7747,
       x__h7749,
       x__h7917,
       x__h7919,
       x__h7921,
       x__h7923,
       x__h7925,
       x__h7927,
       x__h8095,
       x__h8097,
       x__h8099,
       x__h8101,
       x__h8103,
       x__h8105,
       x__h8273,
       x__h8275,
       x__h8277,
       x__h8279,
       x__h8281,
       x__h8283,
       x__h8451,
       x__h8453,
       x__h8455,
       x__h8457,
       x__h8459,
       x__h8461,
       x__h8629,
       x__h8631,
       x__h8633,
       x__h8635,
       x__h8637,
       x__h8639,
       x__h8807,
       x__h8809,
       x__h8811,
       x__h8813,
       x__h8815,
       x__h8985,
       x__h8987,
       x__h8989,
       x__h8991,
       x__h8993,
       x__h9163,
       x__h9165,
       x__h9167,
       x__h9169,
       x__h9171,
       x__h9320,
       x__h9322,
       x__h9324,
       x__h9435,
       x__h9437,
       x__h9439,
       x__h9550;

  // value method calc_crc
  assign calc_crc =
	     { calc_crc_crcIn[47] ^ calc_crc_data[47],
	       x__h1007 ^ calc_crc_data[47],
	       x__h1101 ^ calc_crc_data[46],
	       x__h1195 ^ calc_crc_data[47],
	       calc_crc_crcIn_BIT_43_1_XOR_calc_crc_crcIn_BIT_ETC___d459 } ;

  // remaining internal signals
  assign calc_crc_crcIn_BIT_0_08_XOR_calc_crc_crcIn_BIT_ETC___d437 =
	     { x__h9163 ^ calc_crc_data[3],
	       x__h9320 ^ calc_crc_data[2],
	       x__h9435 ^ calc_crc_data[1],
	       x__h9550 ^ calc_crc_data[0],
	       calc_crc_crcIn[59:48] } ;
  assign calc_crc_crcIn_BIT_11_09_XOR_calc_crc_crcIn_BI_ETC___d443 =
	     { x__h7027 ^ calc_crc_data[15],
	       x__h7205 ^ calc_crc_data[14],
	       x__h7383 ^ calc_crc_data[13],
	       x__h7561 ^ calc_crc_data[12],
	       calc_crc_crcIn_BIT_7_45_XOR_calc_crc_crcIn_BIT_ETC___d441 } ;
  assign calc_crc_crcIn_BIT_15_73_XOR_calc_crc_crcIn_BI_ETC___d445 =
	     { x__h6315 ^ calc_crc_data[19],
	       x__h6493 ^ calc_crc_data[18],
	       x__h6671 ^ calc_crc_data[17],
	       x__h6849 ^ calc_crc_data[16],
	       calc_crc_crcIn_BIT_11_09_XOR_calc_crc_crcIn_BI_ETC___d443 } ;
  assign calc_crc_crcIn_BIT_19_37_XOR_calc_crc_crcIn_BI_ETC___d447 =
	     { x__h5603 ^ calc_crc_data[23],
	       x__h5781 ^ calc_crc_data[22],
	       x__h5959 ^ calc_crc_data[21],
	       x__h6137 ^ calc_crc_data[20],
	       calc_crc_crcIn_BIT_15_73_XOR_calc_crc_crcIn_BI_ETC___d445 } ;
  assign calc_crc_crcIn_BIT_23_01_XOR_calc_crc_crcIn_BI_ETC___d449 =
	     { x__h4891 ^ calc_crc_data[27],
	       x__h5069 ^ calc_crc_data[26],
	       x__h5247 ^ calc_crc_data[25],
	       x__h5425 ^ calc_crc_data[24],
	       calc_crc_crcIn_BIT_19_37_XOR_calc_crc_crcIn_BI_ETC___d447 } ;
  assign calc_crc_crcIn_BIT_27_65_XOR_calc_crc_crcIn_BI_ETC___d451 =
	     { x__h4179 ^ calc_crc_data[31],
	       x__h4357 ^ calc_crc_data[30],
	       x__h4535 ^ calc_crc_data[29],
	       x__h4713 ^ calc_crc_data[28],
	       calc_crc_crcIn_BIT_23_01_XOR_calc_crc_crcIn_BI_ETC___d449 } ;
  assign calc_crc_crcIn_BIT_31_29_XOR_calc_crc_crcIn_BI_ETC___d453 =
	     { x__h3467 ^ calc_crc_data[35],
	       x__h3645 ^ calc_crc_data[34],
	       x__h3823 ^ calc_crc_data[33],
	       x__h4001 ^ calc_crc_data[32],
	       calc_crc_crcIn_BIT_27_65_XOR_calc_crc_crcIn_BI_ETC___d451 } ;
  assign calc_crc_crcIn_BIT_35_3_XOR_calc_crc_crcIn_BIT_ETC___d455 =
	     { x__h2755 ^ calc_crc_data[39],
	       x__h2933 ^ calc_crc_data[38],
	       x__h3111 ^ calc_crc_data[37],
	       x__h3289 ^ calc_crc_data[36],
	       calc_crc_crcIn_BIT_31_29_XOR_calc_crc_crcIn_BI_ETC___d453 } ;
  assign calc_crc_crcIn_BIT_39_7_XOR_calc_crc_crcIn_BIT_ETC___d457 =
	     { x__h2043 ^ calc_crc_data[43],
	       x__h2221 ^ calc_crc_data[42],
	       x__h2399 ^ calc_crc_data[41],
	       x__h2577 ^ calc_crc_data[40],
	       calc_crc_crcIn_BIT_35_3_XOR_calc_crc_crcIn_BIT_ETC___d455 } ;
  assign calc_crc_crcIn_BIT_3_81_XOR_calc_crc_crcIn_BIT_ETC___d439 =
	     { x__h8451 ^ calc_crc_data[7],
	       x__h8629 ^ calc_crc_data[6],
	       x__h8807 ^ calc_crc_data[5],
	       x__h8985 ^ calc_crc_data[4],
	       calc_crc_crcIn_BIT_0_08_XOR_calc_crc_crcIn_BIT_ETC___d437 } ;
  assign calc_crc_crcIn_BIT_43_1_XOR_calc_crc_crcIn_BIT_ETC___d459 =
	     { x__h1331 ^ calc_crc_data[47],
	       x__h1509 ^ calc_crc_data[46],
	       x__h1687 ^ calc_crc_data[45],
	       x__h1865 ^ calc_crc_data[44],
	       calc_crc_crcIn_BIT_39_7_XOR_calc_crc_crcIn_BIT_ETC___d457 } ;
  assign calc_crc_crcIn_BIT_7_45_XOR_calc_crc_crcIn_BIT_ETC___d441 =
	     { x__h7739 ^ calc_crc_data[11],
	       x__h7917 ^ calc_crc_data[10],
	       x__h8095 ^ calc_crc_data[9],
	       x__h8273 ^ calc_crc_data[8],
	       calc_crc_crcIn_BIT_3_81_XOR_calc_crc_crcIn_BIT_ETC___d439 } ;
  assign x__h1007 = x__h1009 ^ calc_crc_data[46] ;
  assign x__h1009 = calc_crc_crcIn[46] ^ calc_crc_crcIn[47] ;
  assign x__h1101 = x__h1103 ^ calc_crc_data[45] ;
  assign x__h1103 = calc_crc_crcIn[45] ^ calc_crc_crcIn[46] ;
  assign x__h1195 = x__h1197 ^ calc_crc_data[45] ;
  assign x__h1197 = x__h1199 ^ calc_crc_data[44] ;
  assign x__h1199 = x__h1201 ^ calc_crc_crcIn[47] ;
  assign x__h1201 = calc_crc_crcIn[44] ^ calc_crc_crcIn[45] ;
  assign x__h1331 = x__h1333 ^ calc_crc_data[46] ;
  assign x__h1333 = x__h1335 ^ calc_crc_data[44] ;
  assign x__h1335 = x__h1337 ^ calc_crc_data[43] ;
  assign x__h1337 = x__h1339 ^ calc_crc_crcIn[47] ;
  assign x__h1339 = x__h1341 ^ calc_crc_crcIn[46] ;
  assign x__h1341 = calc_crc_crcIn[43] ^ calc_crc_crcIn[44] ;
  assign x__h1509 = x__h1511 ^ calc_crc_data[45] ;
  assign x__h1511 = x__h1513 ^ calc_crc_data[43] ;
  assign x__h1513 = x__h1515 ^ calc_crc_data[42] ;
  assign x__h1515 = x__h1517 ^ calc_crc_crcIn[46] ;
  assign x__h1517 = x__h1519 ^ calc_crc_crcIn[45] ;
  assign x__h1519 = calc_crc_crcIn[42] ^ calc_crc_crcIn[43] ;
  assign x__h1687 = x__h1689 ^ calc_crc_data[44] ;
  assign x__h1689 = x__h1691 ^ calc_crc_data[42] ;
  assign x__h1691 = x__h1693 ^ calc_crc_data[41] ;
  assign x__h1693 = x__h1695 ^ calc_crc_crcIn[45] ;
  assign x__h1695 = x__h1697 ^ calc_crc_crcIn[44] ;
  assign x__h1697 = calc_crc_crcIn[41] ^ calc_crc_crcIn[42] ;
  assign x__h1865 = x__h1867 ^ calc_crc_data[43] ;
  assign x__h1867 = x__h1869 ^ calc_crc_data[41] ;
  assign x__h1869 = x__h1871 ^ calc_crc_data[40] ;
  assign x__h1871 = x__h1873 ^ calc_crc_crcIn[44] ;
  assign x__h1873 = x__h1875 ^ calc_crc_crcIn[43] ;
  assign x__h1875 = calc_crc_crcIn[40] ^ calc_crc_crcIn[41] ;
  assign x__h2043 = x__h2045 ^ calc_crc_data[42] ;
  assign x__h2045 = x__h2047 ^ calc_crc_data[40] ;
  assign x__h2047 = x__h2049 ^ calc_crc_data[39] ;
  assign x__h2049 = x__h2051 ^ calc_crc_crcIn[43] ;
  assign x__h2051 = x__h2053 ^ calc_crc_crcIn[42] ;
  assign x__h2053 = calc_crc_crcIn[39] ^ calc_crc_crcIn[40] ;
  assign x__h2221 = x__h2223 ^ calc_crc_data[41] ;
  assign x__h2223 = x__h2225 ^ calc_crc_data[39] ;
  assign x__h2225 = x__h2227 ^ calc_crc_data[38] ;
  assign x__h2227 = x__h2229 ^ calc_crc_crcIn[42] ;
  assign x__h2229 = x__h2231 ^ calc_crc_crcIn[41] ;
  assign x__h2231 = calc_crc_crcIn[38] ^ calc_crc_crcIn[39] ;
  assign x__h2399 = x__h2401 ^ calc_crc_data[40] ;
  assign x__h2401 = x__h2403 ^ calc_crc_data[38] ;
  assign x__h2403 = x__h2405 ^ calc_crc_data[37] ;
  assign x__h2405 = x__h2407 ^ calc_crc_crcIn[41] ;
  assign x__h2407 = x__h2409 ^ calc_crc_crcIn[40] ;
  assign x__h2409 = calc_crc_crcIn[37] ^ calc_crc_crcIn[38] ;
  assign x__h2577 = x__h2579 ^ calc_crc_data[39] ;
  assign x__h2579 = x__h2581 ^ calc_crc_data[37] ;
  assign x__h2581 = x__h2583 ^ calc_crc_data[36] ;
  assign x__h2583 = x__h2585 ^ calc_crc_crcIn[40] ;
  assign x__h2585 = x__h2587 ^ calc_crc_crcIn[39] ;
  assign x__h2587 = calc_crc_crcIn[36] ^ calc_crc_crcIn[37] ;
  assign x__h2755 = x__h2757 ^ calc_crc_data[38] ;
  assign x__h2757 = x__h2759 ^ calc_crc_data[36] ;
  assign x__h2759 = x__h2761 ^ calc_crc_data[35] ;
  assign x__h2761 = x__h2763 ^ calc_crc_crcIn[39] ;
  assign x__h2763 = x__h2765 ^ calc_crc_crcIn[38] ;
  assign x__h2765 = calc_crc_crcIn[35] ^ calc_crc_crcIn[36] ;
  assign x__h2933 = x__h2935 ^ calc_crc_data[37] ;
  assign x__h2935 = x__h2937 ^ calc_crc_data[35] ;
  assign x__h2937 = x__h2939 ^ calc_crc_data[34] ;
  assign x__h2939 = x__h2941 ^ calc_crc_crcIn[38] ;
  assign x__h2941 = x__h2943 ^ calc_crc_crcIn[37] ;
  assign x__h2943 = calc_crc_crcIn[34] ^ calc_crc_crcIn[35] ;
  assign x__h3111 = x__h3113 ^ calc_crc_data[36] ;
  assign x__h3113 = x__h3115 ^ calc_crc_data[34] ;
  assign x__h3115 = x__h3117 ^ calc_crc_data[33] ;
  assign x__h3117 = x__h3119 ^ calc_crc_crcIn[37] ;
  assign x__h3119 = x__h3121 ^ calc_crc_crcIn[36] ;
  assign x__h3121 = calc_crc_crcIn[33] ^ calc_crc_crcIn[34] ;
  assign x__h3289 = x__h3291 ^ calc_crc_data[35] ;
  assign x__h3291 = x__h3293 ^ calc_crc_data[33] ;
  assign x__h3293 = x__h3295 ^ calc_crc_data[32] ;
  assign x__h3295 = x__h3297 ^ calc_crc_crcIn[36] ;
  assign x__h3297 = x__h3299 ^ calc_crc_crcIn[35] ;
  assign x__h3299 = calc_crc_crcIn[32] ^ calc_crc_crcIn[33] ;
  assign x__h3467 = x__h3469 ^ calc_crc_data[34] ;
  assign x__h3469 = x__h3471 ^ calc_crc_data[32] ;
  assign x__h3471 = x__h3473 ^ calc_crc_data[31] ;
  assign x__h3473 = x__h3475 ^ calc_crc_crcIn[35] ;
  assign x__h3475 = x__h3477 ^ calc_crc_crcIn[34] ;
  assign x__h3477 = calc_crc_crcIn[31] ^ calc_crc_crcIn[32] ;
  assign x__h3645 = x__h3647 ^ calc_crc_data[33] ;
  assign x__h3647 = x__h3649 ^ calc_crc_data[31] ;
  assign x__h3649 = x__h3651 ^ calc_crc_data[30] ;
  assign x__h3651 = x__h3653 ^ calc_crc_crcIn[34] ;
  assign x__h3653 = x__h3655 ^ calc_crc_crcIn[33] ;
  assign x__h3655 = calc_crc_crcIn[30] ^ calc_crc_crcIn[31] ;
  assign x__h3823 = x__h3825 ^ calc_crc_data[32] ;
  assign x__h3825 = x__h3827 ^ calc_crc_data[30] ;
  assign x__h3827 = x__h3829 ^ calc_crc_data[29] ;
  assign x__h3829 = x__h3831 ^ calc_crc_crcIn[33] ;
  assign x__h3831 = x__h3833 ^ calc_crc_crcIn[32] ;
  assign x__h3833 = calc_crc_crcIn[29] ^ calc_crc_crcIn[30] ;
  assign x__h4001 = x__h4003 ^ calc_crc_data[31] ;
  assign x__h4003 = x__h4005 ^ calc_crc_data[29] ;
  assign x__h4005 = x__h4007 ^ calc_crc_data[28] ;
  assign x__h4007 = x__h4009 ^ calc_crc_crcIn[32] ;
  assign x__h4009 = x__h4011 ^ calc_crc_crcIn[31] ;
  assign x__h4011 = calc_crc_crcIn[28] ^ calc_crc_crcIn[29] ;
  assign x__h4179 = x__h4181 ^ calc_crc_data[30] ;
  assign x__h4181 = x__h4183 ^ calc_crc_data[28] ;
  assign x__h4183 = x__h4185 ^ calc_crc_data[27] ;
  assign x__h4185 = x__h4187 ^ calc_crc_crcIn[31] ;
  assign x__h4187 = x__h4189 ^ calc_crc_crcIn[30] ;
  assign x__h4189 = calc_crc_crcIn[27] ^ calc_crc_crcIn[28] ;
  assign x__h4357 = x__h4359 ^ calc_crc_data[29] ;
  assign x__h4359 = x__h4361 ^ calc_crc_data[27] ;
  assign x__h4361 = x__h4363 ^ calc_crc_data[26] ;
  assign x__h4363 = x__h4365 ^ calc_crc_crcIn[30] ;
  assign x__h4365 = x__h4367 ^ calc_crc_crcIn[29] ;
  assign x__h4367 = calc_crc_crcIn[26] ^ calc_crc_crcIn[27] ;
  assign x__h4535 = x__h4537 ^ calc_crc_data[28] ;
  assign x__h4537 = x__h4539 ^ calc_crc_data[26] ;
  assign x__h4539 = x__h4541 ^ calc_crc_data[25] ;
  assign x__h4541 = x__h4543 ^ calc_crc_crcIn[29] ;
  assign x__h4543 = x__h4545 ^ calc_crc_crcIn[28] ;
  assign x__h4545 = calc_crc_crcIn[25] ^ calc_crc_crcIn[26] ;
  assign x__h4713 = x__h4715 ^ calc_crc_data[27] ;
  assign x__h4715 = x__h4717 ^ calc_crc_data[25] ;
  assign x__h4717 = x__h4719 ^ calc_crc_data[24] ;
  assign x__h4719 = x__h4721 ^ calc_crc_crcIn[28] ;
  assign x__h4721 = x__h4723 ^ calc_crc_crcIn[27] ;
  assign x__h4723 = calc_crc_crcIn[24] ^ calc_crc_crcIn[25] ;
  assign x__h4891 = x__h4893 ^ calc_crc_data[26] ;
  assign x__h4893 = x__h4895 ^ calc_crc_data[24] ;
  assign x__h4895 = x__h4897 ^ calc_crc_data[23] ;
  assign x__h4897 = x__h4899 ^ calc_crc_crcIn[27] ;
  assign x__h4899 = x__h4901 ^ calc_crc_crcIn[26] ;
  assign x__h4901 = calc_crc_crcIn[23] ^ calc_crc_crcIn[24] ;
  assign x__h5069 = x__h5071 ^ calc_crc_data[25] ;
  assign x__h5071 = x__h5073 ^ calc_crc_data[23] ;
  assign x__h5073 = x__h5075 ^ calc_crc_data[22] ;
  assign x__h5075 = x__h5077 ^ calc_crc_crcIn[26] ;
  assign x__h5077 = x__h5079 ^ calc_crc_crcIn[25] ;
  assign x__h5079 = calc_crc_crcIn[22] ^ calc_crc_crcIn[23] ;
  assign x__h5247 = x__h5249 ^ calc_crc_data[24] ;
  assign x__h5249 = x__h5251 ^ calc_crc_data[22] ;
  assign x__h5251 = x__h5253 ^ calc_crc_data[21] ;
  assign x__h5253 = x__h5255 ^ calc_crc_crcIn[25] ;
  assign x__h5255 = x__h5257 ^ calc_crc_crcIn[24] ;
  assign x__h5257 = calc_crc_crcIn[21] ^ calc_crc_crcIn[22] ;
  assign x__h5425 = x__h5427 ^ calc_crc_data[23] ;
  assign x__h5427 = x__h5429 ^ calc_crc_data[21] ;
  assign x__h5429 = x__h5431 ^ calc_crc_data[20] ;
  assign x__h5431 = x__h5433 ^ calc_crc_crcIn[24] ;
  assign x__h5433 = x__h5435 ^ calc_crc_crcIn[23] ;
  assign x__h5435 = calc_crc_crcIn[20] ^ calc_crc_crcIn[21] ;
  assign x__h5603 = x__h5605 ^ calc_crc_data[22] ;
  assign x__h5605 = x__h5607 ^ calc_crc_data[20] ;
  assign x__h5607 = x__h5609 ^ calc_crc_data[19] ;
  assign x__h5609 = x__h5611 ^ calc_crc_crcIn[23] ;
  assign x__h5611 = x__h5613 ^ calc_crc_crcIn[22] ;
  assign x__h5613 = calc_crc_crcIn[19] ^ calc_crc_crcIn[20] ;
  assign x__h5781 = x__h5783 ^ calc_crc_data[21] ;
  assign x__h5783 = x__h5785 ^ calc_crc_data[19] ;
  assign x__h5785 = x__h5787 ^ calc_crc_data[18] ;
  assign x__h5787 = x__h5789 ^ calc_crc_crcIn[22] ;
  assign x__h5789 = x__h5791 ^ calc_crc_crcIn[21] ;
  assign x__h5791 = calc_crc_crcIn[18] ^ calc_crc_crcIn[19] ;
  assign x__h5959 = x__h5961 ^ calc_crc_data[20] ;
  assign x__h5961 = x__h5963 ^ calc_crc_data[18] ;
  assign x__h5963 = x__h5965 ^ calc_crc_data[17] ;
  assign x__h5965 = x__h5967 ^ calc_crc_crcIn[21] ;
  assign x__h5967 = x__h5969 ^ calc_crc_crcIn[20] ;
  assign x__h5969 = calc_crc_crcIn[17] ^ calc_crc_crcIn[18] ;
  assign x__h6137 = x__h6139 ^ calc_crc_data[19] ;
  assign x__h6139 = x__h6141 ^ calc_crc_data[17] ;
  assign x__h6141 = x__h6143 ^ calc_crc_data[16] ;
  assign x__h6143 = x__h6145 ^ calc_crc_crcIn[20] ;
  assign x__h6145 = x__h6147 ^ calc_crc_crcIn[19] ;
  assign x__h6147 = calc_crc_crcIn[16] ^ calc_crc_crcIn[17] ;
  assign x__h6315 = x__h6317 ^ calc_crc_data[18] ;
  assign x__h6317 = x__h6319 ^ calc_crc_data[16] ;
  assign x__h6319 = x__h6321 ^ calc_crc_data[15] ;
  assign x__h6321 = x__h6323 ^ calc_crc_crcIn[19] ;
  assign x__h6323 = x__h6325 ^ calc_crc_crcIn[18] ;
  assign x__h6325 = calc_crc_crcIn[15] ^ calc_crc_crcIn[16] ;
  assign x__h6493 = x__h6495 ^ calc_crc_data[17] ;
  assign x__h6495 = x__h6497 ^ calc_crc_data[15] ;
  assign x__h6497 = x__h6499 ^ calc_crc_data[14] ;
  assign x__h6499 = x__h6501 ^ calc_crc_crcIn[18] ;
  assign x__h6501 = x__h6503 ^ calc_crc_crcIn[17] ;
  assign x__h6503 = calc_crc_crcIn[14] ^ calc_crc_crcIn[15] ;
  assign x__h6671 = x__h6673 ^ calc_crc_data[16] ;
  assign x__h6673 = x__h6675 ^ calc_crc_data[14] ;
  assign x__h6675 = x__h6677 ^ calc_crc_data[13] ;
  assign x__h6677 = x__h6679 ^ calc_crc_crcIn[17] ;
  assign x__h6679 = x__h6681 ^ calc_crc_crcIn[16] ;
  assign x__h6681 = calc_crc_crcIn[13] ^ calc_crc_crcIn[14] ;
  assign x__h6849 = x__h6851 ^ calc_crc_data[15] ;
  assign x__h6851 = x__h6853 ^ calc_crc_data[13] ;
  assign x__h6853 = x__h6855 ^ calc_crc_data[12] ;
  assign x__h6855 = x__h6857 ^ calc_crc_crcIn[16] ;
  assign x__h6857 = x__h6859 ^ calc_crc_crcIn[15] ;
  assign x__h6859 = calc_crc_crcIn[12] ^ calc_crc_crcIn[13] ;
  assign x__h7027 = x__h7029 ^ calc_crc_data[14] ;
  assign x__h7029 = x__h7031 ^ calc_crc_data[12] ;
  assign x__h7031 = x__h7033 ^ calc_crc_data[11] ;
  assign x__h7033 = x__h7035 ^ calc_crc_crcIn[15] ;
  assign x__h7035 = x__h7037 ^ calc_crc_crcIn[14] ;
  assign x__h7037 = calc_crc_crcIn[11] ^ calc_crc_crcIn[12] ;
  assign x__h7205 = x__h7207 ^ calc_crc_data[13] ;
  assign x__h7207 = x__h7209 ^ calc_crc_data[11] ;
  assign x__h7209 = x__h7211 ^ calc_crc_data[10] ;
  assign x__h7211 = x__h7213 ^ calc_crc_crcIn[14] ;
  assign x__h7213 = x__h7215 ^ calc_crc_crcIn[13] ;
  assign x__h7215 = calc_crc_crcIn[10] ^ calc_crc_crcIn[11] ;
  assign x__h7383 = x__h7385 ^ calc_crc_data[12] ;
  assign x__h7385 = x__h7387 ^ calc_crc_data[10] ;
  assign x__h7387 = x__h7389 ^ calc_crc_data[9] ;
  assign x__h7389 = x__h7391 ^ calc_crc_crcIn[13] ;
  assign x__h7391 = x__h7393 ^ calc_crc_crcIn[12] ;
  assign x__h7393 = calc_crc_crcIn[9] ^ calc_crc_crcIn[10] ;
  assign x__h7561 = x__h7563 ^ calc_crc_data[11] ;
  assign x__h7563 = x__h7565 ^ calc_crc_data[9] ;
  assign x__h7565 = x__h7567 ^ calc_crc_data[8] ;
  assign x__h7567 = x__h7569 ^ calc_crc_crcIn[12] ;
  assign x__h7569 = x__h7571 ^ calc_crc_crcIn[11] ;
  assign x__h7571 = calc_crc_crcIn[8] ^ calc_crc_crcIn[9] ;
  assign x__h7739 = x__h7741 ^ calc_crc_data[10] ;
  assign x__h7741 = x__h7743 ^ calc_crc_data[8] ;
  assign x__h7743 = x__h7745 ^ calc_crc_data[7] ;
  assign x__h7745 = x__h7747 ^ calc_crc_crcIn[11] ;
  assign x__h7747 = x__h7749 ^ calc_crc_crcIn[10] ;
  assign x__h7749 = calc_crc_crcIn[7] ^ calc_crc_crcIn[8] ;
  assign x__h7917 = x__h7919 ^ calc_crc_data[9] ;
  assign x__h7919 = x__h7921 ^ calc_crc_data[7] ;
  assign x__h7921 = x__h7923 ^ calc_crc_data[6] ;
  assign x__h7923 = x__h7925 ^ calc_crc_crcIn[10] ;
  assign x__h7925 = x__h7927 ^ calc_crc_crcIn[9] ;
  assign x__h7927 = calc_crc_crcIn[6] ^ calc_crc_crcIn[7] ;
  assign x__h8095 = x__h8097 ^ calc_crc_data[8] ;
  assign x__h8097 = x__h8099 ^ calc_crc_data[6] ;
  assign x__h8099 = x__h8101 ^ calc_crc_data[5] ;
  assign x__h8101 = x__h8103 ^ calc_crc_crcIn[9] ;
  assign x__h8103 = x__h8105 ^ calc_crc_crcIn[8] ;
  assign x__h8105 = calc_crc_crcIn[5] ^ calc_crc_crcIn[6] ;
  assign x__h8273 = x__h8275 ^ calc_crc_data[7] ;
  assign x__h8275 = x__h8277 ^ calc_crc_data[5] ;
  assign x__h8277 = x__h8279 ^ calc_crc_data[4] ;
  assign x__h8279 = x__h8281 ^ calc_crc_crcIn[8] ;
  assign x__h8281 = x__h8283 ^ calc_crc_crcIn[7] ;
  assign x__h8283 = calc_crc_crcIn[4] ^ calc_crc_crcIn[5] ;
  assign x__h8451 = x__h8453 ^ calc_crc_data[6] ;
  assign x__h8453 = x__h8455 ^ calc_crc_data[4] ;
  assign x__h8455 = x__h8457 ^ calc_crc_data[3] ;
  assign x__h8457 = x__h8459 ^ calc_crc_crcIn[7] ;
  assign x__h8459 = x__h8461 ^ calc_crc_crcIn[6] ;
  assign x__h8461 = calc_crc_crcIn[3] ^ calc_crc_crcIn[4] ;
  assign x__h8629 = x__h8631 ^ calc_crc_data[5] ;
  assign x__h8631 = x__h8633 ^ calc_crc_data[3] ;
  assign x__h8633 = x__h8635 ^ calc_crc_data[2] ;
  assign x__h8635 = x__h8637 ^ calc_crc_crcIn[6] ;
  assign x__h8637 = x__h8639 ^ calc_crc_crcIn[5] ;
  assign x__h8639 = calc_crc_crcIn[2] ^ calc_crc_crcIn[3] ;
  assign x__h8807 = x__h8809 ^ calc_crc_data[4] ;
  assign x__h8809 = x__h8811 ^ calc_crc_data[2] ;
  assign x__h8811 = x__h8813 ^ calc_crc_data[1] ;
  assign x__h8813 = x__h8815 ^ calc_crc_crcIn[5] ;
  assign x__h8815 = x__h9324 ^ calc_crc_crcIn[4] ;
  assign x__h8985 = x__h8987 ^ calc_crc_data[3] ;
  assign x__h8987 = x__h8989 ^ calc_crc_data[1] ;
  assign x__h8989 = x__h8991 ^ calc_crc_data[0] ;
  assign x__h8991 = x__h8993 ^ calc_crc_crcIn[4] ;
  assign x__h8993 = x__h9439 ^ calc_crc_crcIn[3] ;
  assign x__h9163 = x__h9165 ^ calc_crc_data[2] ;
  assign x__h9165 = x__h9167 ^ calc_crc_data[0] ;
  assign x__h9167 = x__h9169 ^ calc_crc_crcIn[63] ;
  assign x__h9169 = x__h9171 ^ calc_crc_crcIn[3] ;
  assign x__h9171 = calc_crc_crcIn[0] ^ calc_crc_crcIn[2] ;
  assign x__h9320 = x__h9322 ^ calc_crc_data[1] ;
  assign x__h9322 = x__h9324 ^ calc_crc_crcIn[62] ;
  assign x__h9324 = calc_crc_crcIn[1] ^ calc_crc_crcIn[2] ;
  assign x__h9435 = x__h9437 ^ calc_crc_data[0] ;
  assign x__h9437 = x__h9439 ^ calc_crc_crcIn[61] ;
  assign x__h9439 = calc_crc_crcIn[0] ^ calc_crc_crcIn[1] ;
  assign x__h9550 = calc_crc_crcIn[0] ^ calc_crc_crcIn[60] ;
endmodule  // module_calc_crc

